export const text = {
  home: "خانه",
  product: "محصولات",
  offers: "تخفیف و پیشنهادات",
  questions: "سوالات متداول",
  profile: "پروفایل کابری",
  cart: "سبدخرید",
  payMent: "پرداخت",
  airPod: "ایرپاد",
  charger: "شارژر",
  powerBank: "پاوربانک",
  cover: "قاب",
  headphone: "هدفون",
  flash: "فلش",
  memory: "مموری",
  watch: "ساعت",
  logIn: "ورود",
  signUp: "ثبت نام",
};
